<a name='0'></a>
# Intro #

## Table of Contents ##
- [a](#0)
- [b](#1)
- [c](#2)

<a name='1'></a>
# 1-NumPy arrays #

In [195]:
import numpy as np

In [196]:
# Create an array with 3 integers, starting from the default integer 0.
b = np.arange(3)
print(b)

[0 1 2]


In [197]:
# Create an array that starts from the integer 1, ends at 20, incremented by 3.
c = np.arange(1, 22, 3, dtype=float)
print(c)

[ 1.  4.  7. 10. 13. 16. 19.]


In [198]:
# evenly spaced numbers over a specified interval.
lin_spaced_arr = np.linspace(0, 100, 6)
print(lin_spaced_arr)
print(lin_spaced_arr.dtype)  # Prints the data type of the array

[  0.  20.  40.  60.  80. 100.]
float64


In [199]:
# Return a new array of shape 3, filled with ones.
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [200]:
# Return a new array of shape 3, filled with zeroes.
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [201]:
# Return a new array of shape 3, without initializing entries.
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


In [202]:
# Return a new array of shape 3 with random numbers between 0 and 1.
rand_arr = np.random.rand(3)
print(rand_arr)

[0.41461611 0.03394832 0.9679867 ]


<a name='2'></a>
# 2 - Multidimensional Arrays #

In [203]:
# Create a 2 dimensional array (2-D)
two_dim_arr = np.array([[1, 2, 3], [4, 5, 6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


In [204]:
# 1-D array
one_dim_arr = np.array([1, 2, 3, 4, 5, 6])

# Multidimensional array using reshape()
multi_dim_arr = np.reshape(
    one_dim_arr,  # the array to be reshaped
    (2, 3)  # dimensions of the new array
)
# Print the new 2-D array with two rows and three columns
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


<a name='2-1'></a>
## 2.1 - Finding size, shape and dimension. ##

In [205]:
# Dimension of the 2-D array multi_dim_arr
multi_dim_arr.ndim

2

In [206]:
# Shape of the 2-D array multi_dim_arr
# Returns shape of 2 rows and 3 columns
multi_dim_arr.shape

(2, 3)

In [207]:
# Size of the array multi_dim_arr
# Returns total number of elements
multi_dim_arr.size

6

<a name='3'></a>
# 3 - Array math operations #

In [208]:

arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])
# Multiplying two 1-D arrays elementwise
multiplication = arr_1 * arr_2
print(multiplication)

[ 2 12 30]


<a name='3-1'></a>
## 3.1 - Multiplying vector with a scalar (broadcasting) ##

In [209]:
vector = np.array([1, 2])
vector * 1.6

array([1.6, 3.2])

<a name='4'></a>
# 4 - Indexing and slicing #

## 4.1 - Indexing ##


In [210]:
# Indexing on a 2-D array
two_dim = np.array(([1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]))
# two ways
print(two_dim[2][1])
print(two_dim[2, 1])

8
8


<a name='4-2'></a>
## 4.2 - Slicing ##

In [211]:
a = np.array([1, 2, 3, 4, 5])

In [212]:
# Slice the array a to get the array [1,3,5]
sliced_arr = a[::2]
print(sliced_arr)

# Note that a == a[:] == a[::]

[1 3 5]


In [213]:
sliced_two_dim_cols = two_dim[1:3, 1]
print(two_dim)
print(sliced_two_dim_cols)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[5 8]


<a name='5'></a>
# 5 - Stacking #
It means to join two or more arrays, either horizontally or vertically, meaning that it is done along a new axis. 

- `np.vstack()` - stacks vertically
- `np.hstack()` - stacks horizontally
- `np.hsplit()` - splits an array into several smaller arrays

In [214]:
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
              [4, 4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [215]:
# Stack the arrays vertically
vert_stack = np.vstack((a1, a2))
print(vert_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [216]:
# Stack the arrays horizontally
horz_stack = np.hstack((a1, a2))
print(horz_stack)

[[1 1 3 3]
 [2 2 4 4]]


In [217]:
# Split the horizontally stacked array into 2 separate arrays of equal size
horz_split_two = np.hsplit(horz_stack, 2)
print(horz_split_two)

# Split the horizontally stacked array into 4 separate arrays of equal size
horz_split_four = np.hsplit(horz_stack, 4)
print(horz_split_four)

# Split the horizontally stacked array after the first column
horz_split_first = np.hsplit(horz_stack, [1])
print(horz_split_first)

[array([[1, 1],
       [2, 2]]), array([[3, 3],
       [4, 4]])]
[array([[1],
       [2]]), array([[1],
       [2]]), array([[3],
       [4]]), array([[3],
       [4]])]
[array([[1],
       [2]]), array([[1, 3, 3],
       [2, 4, 4]])]


In [218]:
# Split the vertically stacked array into 2 separate arrays of equal size
vert_split_two = np.vsplit(vert_stack, 2)
print(vert_split_two)

# Split the horizontally stacked array into 4 separate arrays of equal size
vert_split_four = np.vsplit(vert_stack, 4)
print(vert_split_four)

# Split the horizontally stacked array after the first and third row
vert_split_first_third = np.vsplit(vert_stack, [1, 3])
print(vert_split_first_third)

[array([[1, 1],
       [2, 2]]), array([[3, 3],
       [4, 4]])]
[array([[1, 1]]), array([[2, 2]]), array([[3, 3]]), array([[4, 4]])]
[array([[1, 1]]), array([[2, 2],
       [3, 3]]), array([[4, 4]])]


<a name='6'></a>
# 6 - Vector Operations: Scalar Multiplication, Sum and Dot Product of Vectors

In [219]:
v = np.array([[1], [3]])
w = np.array([[4], [-1]])

In [220]:
print("Norm of a vector v is", np.linalg.norm(v))

Norm of a vector v is 3.1622776601683795


<a name='6.1'></a>
### 6.1 - Dot Product using Python

In [221]:
x = [1, -2, -5]
y = [4, 3, -1]
print("The dot product of x and y is", np.dot(x, y))

The dot product of x and y is 3


Note that you did not have to define vectors $x$ and $y$ as `NumPy` arrays, the function worked even with the lists. But there are alternative functions in Python, such as explicit operator `@` for the dot product, which can be applied only to the `NumPy` arrays. You can run the following cell to check that.

In [222]:
# print(x @ y)
# TypeError: unsupported operand type(s) for @: 'list' and 'list'

In [223]:
np.array(x) @ np.array(y)

3

<a name='7'></a>
## 7 - Definition of Matrix Multiplication

In [224]:
A = np.array([[4, 9, 9], [9, 1, 6], [9, 2, 3]])
print("Matrix A (3 by 3):\n", A)

B = np.array([[2, 2], [5, 7], [4, 4]])
print("Matrix B (3 by 2):\n", B)

Matrix A (3 by 3):
 [[4 9 9]
 [9 1 6]
 [9 2 3]]
Matrix B (3 by 2):
 [[2 2]
 [5 7]
 [4 4]]


You can multiply matrices $A$ and $B$ using `NumPy` package function `np.matmul()`:

In [225]:
np.matmul(A, B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

Which will output $3 \times 2$ matrix as a `np.array`. Python operator `@` will also work here giving the same result:

In [226]:
A @ B

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

### dot 

In [227]:
np.dot(A, B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

<a name='8'></a>
# 8 - eigenvalues and eigenvectors

In [228]:
import numpy as np

In [229]:
A = np.array([[2, 3], [2, 1]])
e1 = np.array([[1], [0]])
e2 = np.array([[0], [1]])

In [230]:
A_eig = np.linalg.eig(A)

print(f"Matrix A:\n{A}")
print(f"Eigenvalues of matrix A:\n{A_eig[0]}\n")
print(f"Eigenvectors of matrix A:\n{A_eig[1]}")

Matrix A:
[[2 3]
 [2 1]]
Eigenvalues of matrix A:
[ 4. -1.]

Eigenvectors of matrix A:
[[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]


In [231]:
#  first eigenvector
print(A_eig[1][:, 0])
#  second eigenvector
print(A_eig[1][:, 1])

[0.83205029 0.5547002 ]
[-0.70710678  0.70710678]


# other

In [232]:
# The usage of np.isclose is a good practice when comparing two floats.
np.isclose(1, 0)

False

In [233]:
# cov_matrix = np.cov(X, rowvar=False)