# Intro

In [ ]:
import numpy as np

In [ ]:
A = np.array([
    [-1, 3],
    [3, 2]
], dtype=np.dtype(float))

b = np.array([7, 1], dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)

Matrix A:
[[-1.  3.]
 [ 3.  2.]]

Array b:
[7. 1.]


## solve Ax=b

In [4]:
# Linear Algebra - Lab: Solving a System of Linear Equations with NumPy
x = np.linalg.solve(A, b)
print(x)

[-1.  2.]


In [ ]:
# Determinant of matrix
det_A = np.linalg.det(A)
print(f"Determinant of matrix A: {det_A:.2f}")

Determinant of matrix A: -11.00


In [7]:
# Representation of the system as a matrix
A_system = np.hstack((A, b.reshape((2, 1))))

print(A_system)

[[-1.  3.  7.]
 [ 3.  2.  1.]]
